# MODE DEVELOPPEMENT
spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true

# Désactive le cache de Thymeleaf pour voir les modifs en direct
spring.thymeleaf.cache=false

# Affiche plus de détails dans la console
# debug=true

# SERVEUR
server.port=8080

# BASE DE DONNEES MYSQL
spring.datasource.url=jdbc:mysql://localhost:3306/note_db
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# JPA (Hibernate)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
logging.level.org.hibernate.type.descriptor.sql=OFF

# THYMELEAF
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.mode=HTML